version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        expose:
            - "9000"
        volumes:
            - .:/var/www
        networks:
            - laravel-network
        command: >
            sh -c "
            until php -r 'new PDO(\"mysql:host=db;dbname=laravel\", \"root\", \"root\");'; do
                echo 'Waiting for database...';
                sleep 2;
            done;
            composer install --no-interaction --prefer-dist;
            php artisan migrate --path=/database/migrations/2024_12_01_152944_create_marvel_character.php;
            php artisan db:seed --class=MarvelCharactersSeeder;
            php-fpm
            "
    web:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel-network

    db:
        image: mysql:5.7
        container_name: mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge

